export type StructureType = "commune" | "epci" | "department" | "region";
export type ServiceCategory = "lst" | "other";

export type ServiceConfig = {
  visible: boolean;
  definition: string;
  available_for: StructureType[];
  category: ServiceCategory;
  shortname: string | null;
  order: number;
  anct_threshold_active: boolean;
};

const servicesConfig: Record<string, ServiceConfig> = {
  "Accompagnement Numérique Sur Mesure": {
    visible: true,
    definition: "Collectivités accompagnées. Lancé en 2022",
    available_for: ["commune", "epci"],
    category: "other",
    shortname: "Accompagnement num. sur mesure",
    order: 15,
    anct_threshold_active: false,
  },
  "Administration +": {
    visible: true,
    definition: "Commune où un utilisateur est actif",
    available_for: ["commune"],
    category: "other",
    shortname: null,
    order: 12,
    anct_threshold_active: false,
  },
  "Agents en intervention": {
    visible: false,
    definition: "",
    available_for: [],
    category: "lst",
    shortname: null,
    order: 0,
    anct_threshold_active: false,
  },
  "Aides-territoires": {
    visible: true,
    definition: "Communes qui utilisent le service. Lancé en 2018",
    available_for: ["commune", "epci"],
    category: "other",
    shortname: null,
    order: 13,
    anct_threshold_active: false,
  },
  "Annuaire des Collectivités": {
    visible: true,
    definition: "Collectivités ayant certifié leurs informations locales. Lancé en 2022",
    available_for: ["commune"],
    category: "lst",
    shortname: null,
    order: 5,
    anct_threshold_active: false,
  },
  Calendriers: {
    visible: false,
    definition: "",
    available_for: [],
    category: "lst",
    shortname: null,
    order: 0,
    anct_threshold_active: false,
  },
  Deveco: {
    visible: true,
    definition: "Structures qui utilisent le service. Lancé en 2021",
    available_for: ["commune", "epci", "department", "region"],
    category: "lst",
    shortname: null,
    order: 10,
    anct_threshold_active: false,
  },
  Docs: {
    visible: false,
    definition: "",
    available_for: [],
    category: "lst",
    shortname: null,
    order: 0,
    anct_threshold_active: false,
  },
  "Espace sur Demande": {
    visible: true,
    definition: "Collectivités qui mettent à disposition un espace public. Lancé en 2017",
    available_for: ["commune", "epci"],
    category: "lst",
    shortname: null,
    order: 9,
    anct_threshold_active: true,
  },
  Fichiers: {
    visible: true,
    definition: "Collectivités qui utilisent le service. Lancé en 2026",
    available_for: ["commune", "epci"],
    category: "lst",
    shortname: null,
    order: 3,
    anct_threshold_active: false,
  },
  Grist: {
    visible: true,
    definition: "Collectivités qui utilisent le service. Lancé en 2021",
    available_for: ["commune", "epci"],
    category: "lst",
    shortname: null,
    order: 8,
    anct_threshold_active: false,
  },
  "Mes Adresses": {
    visible: true,
    definition: "Collectivités ayant publié une base adresse locale. Lancé en 2020",
    available_for: ["commune", "epci"],
    category: "lst",
    shortname: null,
    order: 6,
    anct_threshold_active: false,
  },
  "Mes Services Cyber": {
    visible: false,
    definition: "",
    available_for: [],
    category: "lst",
    shortname: null,
    order: 0,
    anct_threshold_active: false,
  },
  Messages: {
    visible: true,
    definition: "Collectivités qui utilisent le service. Lancé en 2026",
    available_for: ["commune", "epci"],
    category: "lst",
    shortname: null,
    order: 2,
    anct_threshold_active: false,
  },
  "Mon Espace Collectivité": {
    visible: true,
    definition: "Communes qui utilisent le service. Lancé en 2023",
    available_for: ["commune", "epci"],
    category: "other",
    shortname: null,
    order: 14,
    anct_threshold_active: false,
  },
  "Mon Service Sécurisé": {
    visible: false,
    definition: "",
    available_for: [],
    category: "lst",
    shortname: null,
    order: 0,
    anct_threshold_active: false,
  },
  "Mon Suivi Social": {
    visible: true,
    definition: "Structures qui utilisent le service. Lancé en 2021",
    available_for: ["commune", "epci"],
    category: "lst",
    shortname: null,
    order: 11,
    anct_threshold_active: false,
  },
  ProConnect: {
    visible: true,
    definition: "Structures qui utilisent l'identification ProConnect",
    available_for: ["commune", "epci", "department", "region"],
    category: "lst",
    shortname: null,
    order: 1,
    anct_threshold_active: false,
  },
  Projets: {
    visible: true,
    definition: "Collectivités qui utilisent le service. Lancé en 2026",
    available_for: ["commune", "epci"],
    category: "lst",
    shortname: null,
    order: 7,
    anct_threshold_active: false,
  },
  "Rendez-vous": {
    visible: true,
    definition: "Structures qui utilisent le service. Lancé en 2018",
    available_for: ["commune", "epci", "department", "region"],
    category: "lst",
    shortname: null,
    order: 4,
    anct_threshold_active: true,
  },
  "Toutes et tous connecté·e·s": {
    visible: false,
    definition: "",
    available_for: [],
    category: "lst",
    shortname: null,
    order: 0,
    anct_threshold_active: false,
  },
  Visio: {
    visible: false,
    definition: "",
    available_for: [],
    category: "lst",
    shortname: null,
    order: 0,
    anct_threshold_active: false,
  },
};

export default servicesConfig;
