#!/bin/bash

set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output

echo "-----> Running post-compile script"

# Remove some files that are not needed

# Keep only next-swc.linux-x64-gnu.node
rm -rf ./node_modules/@next/swc-linux-x64-musl
rm -rf ./node_modules/next/next-swc-fallback/@next/swc-linux-x64-musl
rm -rf ./node_modules/@img/sharp-libvips-linuxmusl-x64
rm -rf ./node_modules/@swc/core/node_modules/@swc/core-linux-x64-musl
rm -rf ./node_modules/@swc/core-linux-x64-musl
find node_modules -type f -name '*.map' -delete

if [ "$PRODUCTION_SOURCE_MAPS" != "1" ]; then
  find .next -type f -name '*.map' -delete
fi

rm -rf .next/cache
rm -rf .cache

# echo "-----> Listing top files/dirs by size"
# du -ah . | sort -rh | head -n 100

exit 0