name: Deploy main in production

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    # Deploy if the tests passed and the branch is main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add Scalingo to known_hosts
        run: mkdir -p ~/.ssh && ssh-keyscan -H ssh.osc-secnum-fr1.scalingo.com >> ~/.ssh/known_hosts
      - name: Setup SSH key
        env:
          SCALINGO_PRIVATE_KEY_BASE64: ${{ secrets.SCALINGO_PRIVATE_KEY_BASE64 }}
        run: |
          mkdir -p ~/.ssh
          echo "$SCALINGO_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Deploy on Scalingo
        env:
          SCALINGO_APP: ${{ secrets.SCALINGO_APP }}
        run: git push -f git@ssh.osc-secnum-fr1.scalingo.com:${SCALINGO_APP}.git main
